"""add activity_metrics and weekly_training tables

Revision ID: 0f8f8781f451
Revises: bbe1ab0c2a71
Create Date: 2026-07-18 16:20:45.933103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f8f8781f451'
down_revision: Union[str, Sequence[str], None] = 'bbe1ab0c2a71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.String(length=64), nullable=False),
    sa.Column('discipline', sa.String(length=16), nullable=True),
    sa.Column('tss', sa.Float(), nullable=True),
    sa.Column('intensity_factor', sa.Float(), nullable=True),
    sa.Column('tss_method', sa.String(length=16), nullable=True),
    sa.Column('bike_tss', sa.Float(), nullable=True),
    sa.Column('run_tss', sa.Float(), nullable=True),
    sa.Column('swim_tss', sa.Float(), nullable=True),
    sa.Column('zone_distribution', sa.JSON(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', name='uq_activity_metrics_activity_id')
    )
    with op.batch_alter_table('activity_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_metrics_activity_id'), ['activity_id'], unique=False)

    op.create_table('weekly_training',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('total_tss', sa.Float(), nullable=True),
    sa.Column('bike_tss', sa.Float(), nullable=True),
    sa.Column('run_tss', sa.Float(), nullable=True),
    sa.Column('swim_tss', sa.Float(), nullable=True),
    sa.Column('total_hours', sa.Float(), nullable=True),
    sa.Column('bike_hours', sa.Float(), nullable=True),
    sa.Column('run_hours', sa.Float(), nullable=True),
    sa.Column('swim_hours', sa.Float(), nullable=True),
    sa.Column('bike_distance', sa.Float(), nullable=True),
    sa.Column('run_distance', sa.Float(), nullable=True),
    sa.Column('swim_distance', sa.Float(), nullable=True),
    sa.Column('ctl', sa.Float(), nullable=True),
    sa.Column('atl', sa.Float(), nullable=True),
    sa.Column('tsb', sa.Float(), nullable=True),
    sa.Column('longest_run', sa.Float(), nullable=True),
    sa.Column('longest_bike', sa.Float(), nullable=True),
    sa.Column('longest_swim', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_start', name='uq_weekly_training_week_start')
    )
    with op.batch_alter_table('weekly_training', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_training_week_start'), ['week_start'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_training', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_training_week_start'))

    op.drop_table('weekly_training')
    with op.batch_alter_table('activity_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_metrics_activity_id'))

    op.drop_table('activity_metrics')
    # ### end Alembic commands ###
