"""initial schema: activities, activity_raw, athlete_settings

Revision ID: bbe1ab0c2a71
Revises: 
Create Date: 2026-07-18 16:11:04.987461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbe1ab0c2a71'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.String(length=64), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('activity_name', sa.String(length=255), nullable=True),
    sa.Column('sport', sa.String(length=64), nullable=True),
    sa.Column('subsport', sa.String(length=64), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('avg_hr', sa.Float(), nullable=True),
    sa.Column('max_hr', sa.Float(), nullable=True),
    sa.Column('avg_power', sa.Float(), nullable=True),
    sa.Column('normalized_power', sa.Float(), nullable=True),
    sa.Column('pace', sa.Float(), nullable=True),
    sa.Column('elevation_gain', sa.Float(), nullable=True),
    sa.Column('source_data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', name='uq_activities_activity_id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_activity_id'), ['activity_id'], unique=False)

    op.create_table('activity_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.String(length=64), nullable=False),
    sa.Column('garmin_json', sa.JSON(), nullable=False),
    sa.Column('import_timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', name='uq_activity_raw_activity_id')
    )
    with op.batch_alter_table('activity_raw', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_raw_activity_id'), ['activity_id'], unique=False)

    op.create_table('athlete_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.String(length=64), nullable=False),
    sa.Column('ftp_watts', sa.Integer(), nullable=True),
    sa.Column('run_threshold_pace_seconds_per_km', sa.Float(), nullable=True),
    sa.Column('swim_css_pace_seconds_per_100m', sa.Float(), nullable=True),
    sa.Column('max_hr', sa.Integer(), nullable=True),
    sa.Column('resting_hr', sa.Integer(), nullable=True),
    sa.Column('threshold_hr', sa.Integer(), nullable=True),
    sa.Column('hr_zones', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', name='uq_athlete_settings_athlete_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('athlete_settings')
    with op.batch_alter_table('activity_raw', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_raw_activity_id'))

    op.drop_table('activity_raw')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_activity_id'))

    op.drop_table('activities')
    # ### end Alembic commands ###
